# Site settings
title: SustainTech Lab
email: me@antonellasuccurro.eu
url: https://sustain-tech-lab.github.io
description: "Servizi di consulenza tecnica per lo sviluppo software, analisi dati territoriali ed ambientali, e supporto a ricerca & sviluppo. Training e workshops su innovazione, sostenibilità e tecnologia."
keywords: ""
skills: "Software Dev • GIS Analysis • Data Science • R&D • Training"
meta_author: "SustainTech Lab"

# Disable integrations
google_verify:
bing_verify:

# Color settings
color:
  primary: 18bc9c
  primary-rgb: "24,188,156"
  secondary: 2c3e50
  secondary-dark: 233140

# Footer settings
footer:
  copyright: SustainTech Lab
  location: 
  social: 
  credits: 

# Social networks (lasciati vuoti per nascondere le icone nel footer)
social: []

# Postal address (vuoto)
address: []

# Build settings
markdown: kramdown
permalink: pretty
